import { GROWTH_CHART_CATALOG } from '@/lib/growthCharts/catalog';
import type { ClinicalChartDef } from './types';
import {
  DLQI_ZONES,
  EVA_ZONES,
  GAD7_ZONES,
  PASI_ZONES,
  PHQ9_ZONES,
  SCORAD_ZONES,
} from './zones';

const PEDIATRIC_LMS: ClinicalChartDef[] = GROWTH_CHART_CATALOG.map((g) => ({
  id: g.id,
  group: 'pediatria' as const,
  kind: 'lms-age' as const,
  label: g.label,
  measureKey: g.measureKey,
  yLabel: g.yLabel,
  source: g.source,
  lmsIndicator: g.indicator,
  ageMinMonths: g.ageMinMonths,
  ageMaxMonths: g.ageMaxMonths,
  requiresBirthDate: true,
  requiresSex: true,
}));

const CARDIOMETABOLIC: ClinicalChartDef[] = [
  {
    id: 'esc-pa-sistolica',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'PA sistólica ao longo do tempo',
    measureKey: 'pa_sistolica',
    yLabel: 'PA sistólica (mmHg)',
    source: 'ESC / AHA — metas terapêuticas',
    goals: [
      { value: 120, label: 'Ideal <120', color: '#86efac' },
      { value: 130, label: 'Meta <130', color: '#fde047' },
      { value: 140, label: 'Estágio 1', color: '#fdba74' },
    ],
    yMax: 200,
  },
  {
    id: 'esc-pa-diastolica',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'PA diastólica ao longo do tempo',
    measureKey: 'pa_diastolica',
    yLabel: 'PA diastólica (mmHg)',
    source: 'ESC / AHA — metas terapêuticas',
    goals: [
      { value: 80, label: 'Ideal <80', color: '#86efac' },
      { value: 90, label: 'Meta <90', color: '#fde047' },
    ],
    yMax: 120,
  },
  {
    id: 'ada-glicemia',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'Glicemia ao longo do tempo',
    measureKey: 'glicemia',
    yLabel: 'Glicemia (mg/dL)',
    source: 'ADA — metas glicêmicas',
    goals: [
      { value: 70, label: 'Limite inferior', color: '#93c5fd' },
      { value: 99, label: 'Jejum normal <100', color: '#86efac' },
      { value: 126, label: 'Diabetes ≥126', color: '#fca5a5' },
      { value: 180, label: 'Pós-prandial meta', color: '#fde047' },
    ],
    yMax: 400,
  },
  {
    id: 'ada-hba1c',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'HbA1c ao longo do tempo',
    measureKey: 'hba1c',
    yLabel: 'HbA1c (%)',
    source: 'ADA — metas de controle',
    goals: [
      { value: 7, label: 'Meta geral <7%', color: '#86efac' },
      { value: 6.5, label: 'Meta intensiva <6,5%', color: '#bbf7d0' },
      { value: 8, label: 'Atenção ≥8%', color: '#fca5a5' },
    ],
    yMax: 14,
  },
  {
    id: 'esc-ldl',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'LDL ao longo do tempo',
    measureKey: 'ldl',
    yLabel: 'LDL (mg/dL)',
    source: 'ESC/EAS — metas lipídicas',
    goals: [
      { value: 55, label: 'Muito alto risco <55', color: '#86efac' },
      { value: 70, label: 'Alto risco <70', color: '#bbf7d0' },
      { value: 100, label: 'Risco moderado <100', color: '#fde047' },
      { value: 116, label: 'Baixo risco <116', color: '#fed7aa' },
    ],
    yMax: 250,
  },
  {
    id: 'oms-imc-adulto',
    group: 'cardiometabolico',
    kind: 'time-goals',
    label: 'IMC ao longo do tempo',
    measureKey: 'imc',
    yLabel: 'IMC (kg/m²)',
    source: 'OMS — classificação adulto',
    goals: [
      { value: 18.5, label: 'Baixo peso', color: '#93c5fd' },
      { value: 25, label: 'Sobrepeso ≥25', color: '#fde047' },
      { value: 30, label: 'Obesidade ≥30', color: '#fca5a5' },
    ],
    yMax: 45,
  },
  {
    id: 'peso-serial',
    group: 'cardiometabolico',
    kind: 'time-plain',
    label: 'Peso ao longo do tempo',
    measureKey: 'peso_kg',
    yLabel: 'Peso (kg)',
    source: 'Acompanhamento serial',
  },
  {
    id: 'creatinina-tfg',
    group: 'cardiometabolico',
    kind: 'time-plain',
    label: 'Creatinina / função renal',
    measureKey: 'creatinina',
    yLabel: 'Creatinina (mg/dL)',
    source: 'KDIGO — acompanhamento',
  },
];

const ONCOLOGY: ClinicalChartDef[] = [
  {
    id: 'recist-sumatorio',
    group: 'oncologia',
    kind: 'time-recist',
    label: 'RECIST — soma lesões-alvo (mm)',
    measureKey: 'sumatorio_lesoes_mm',
    yLabel: 'Soma diâmetros (mm)',
    source: 'RECIST 1.1 — resposta tumoral',
  },
  {
    id: 'recist-carga-pct',
    group: 'oncologia',
    kind: 'time-recist',
    label: 'RECIST — carga tumoral (% vs basal)',
    measureKey: 'carga_tumoral_pct',
    yLabel: 'Variação (%)',
    source: 'RECIST 1.1 — PR −30% / PD +20%',
  },
  {
    id: 'marcador-cea',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'CEA',
    measureKey: 'cea',
    yLabel: 'CEA (ng/mL)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
  {
    id: 'marcador-ca125',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'CA-125',
    measureKey: 'ca125',
    yLabel: 'CA-125 (U/mL)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
  {
    id: 'marcador-psa',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'PSA',
    measureKey: 'psa',
    yLabel: 'PSA (ng/mL)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
  {
    id: 'marcador-afp',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'AFP',
    measureKey: 'afp',
    yLabel: 'AFP (ng/mL)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
  {
    id: 'marcador-ca19',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'CA 19-9',
    measureKey: 'ca19_9',
    yLabel: 'CA 19-9 (U/mL)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
  {
    id: 'marcador-ldh',
    group: 'oncologia',
    kind: 'time-plain',
    label: 'LDH',
    measureKey: 'ldh',
    yLabel: 'LDH (U/L)',
    source: 'Marcador tumoral — acompanhamento serial',
  },
];

const SCALES: ClinicalChartDef[] = [
  {
    id: 'escala-phq9',
    group: 'escalas',
    kind: 'time-zones',
    label: 'PHQ-9 — depressão',
    measureKey: 'phq9',
    yLabel: 'PHQ-9',
    source: 'APA / Kroenke et al.',
    zones: PHQ9_ZONES,
    yMax: 27,
  },
  {
    id: 'escala-gad7',
    group: 'escalas',
    kind: 'time-zones',
    label: 'GAD-7 — ansiedade',
    measureKey: 'gad7',
    yLabel: 'GAD-7',
    source: 'Spitzer et al.',
    zones: GAD7_ZONES,
    yMax: 21,
  },
  {
    id: 'escala-pasi',
    group: 'escalas',
    kind: 'time-zones',
    label: 'PASI — psoríase',
    measureKey: 'pasi',
    yLabel: 'PASI',
    source: 'EADV / AAD',
    zones: PASI_ZONES,
    yMax: 72,
  },
  {
    id: 'escala-scorad',
    group: 'escalas',
    kind: 'time-zones',
    label: 'SCORAD — dermatite atópica',
    measureKey: 'scorad',
    yLabel: 'SCORAD',
    source: 'European Task Force',
    zones: SCORAD_ZONES,
    yMax: 103,
  },
  {
    id: 'escala-dlqi',
    group: 'escalas',
    kind: 'time-zones',
    label: 'DLQI — qualidade de vida (pele)',
    measureKey: 'dlqi',
    yLabel: 'DLQI',
    source: 'Dermatology Life Quality Index',
    zones: DLQI_ZONES,
    yMax: 30,
  },
  {
    id: 'escala-eva',
    group: 'escalas',
    kind: 'time-zones',
    label: 'EVA — dor',
    measureKey: 'eva_dor',
    yLabel: 'EVA (0–10)',
    source: 'Escala visual analógica',
    zones: EVA_ZONES,
    yMax: 10,
  },
];

const PNEUMO: ClinicalChartDef[] = [
  {
    id: 'pneumo-fev1',
    group: 'pneumo',
    kind: 'time-plain',
    label: 'FEV1 ao longo do tempo',
    measureKey: 'fev1',
    yLabel: 'FEV1 (L)',
    source: 'GOLD — espirometria serial',
  },
  {
    id: 'pneumo-cvf',
    group: 'pneumo',
    kind: 'time-plain',
    label: 'CVF ao longo do tempo',
    measureKey: 'cvf',
    yLabel: 'CVF (L)',
    source: 'GOLD — espirometria serial',
  },
  {
    id: 'pneumo-spo2',
    group: 'pneumo',
    kind: 'time-goals',
    label: 'SpO₂ ao longo do tempo',
    measureKey: 'saturacao',
    yLabel: 'SpO₂ (%)',
    source: 'Metas de oxigenação',
    goals: [
      { value: 94, label: 'Meta ≥94%', color: '#86efac' },
      { value: 90, label: 'Atenção <90%', color: '#fca5a5' },
    ],
    yMax: 100,
  },
];

export const CLINICAL_CHART_CATALOG: ClinicalChartDef[] = [
  ...PEDIATRIC_LMS,
  ...CARDIOMETABOLIC,
  ...ONCOLOGY,
  ...SCALES,
  ...PNEUMO,
];

export const CATALOG_MEASURE_KEYS = new Set(
  CLINICAL_CHART_CATALOG.map((c) => c.measureKey),
);

export function chartsForGroup(group: ClinicalChartDef['group']): ClinicalChartDef[] {
  return CLINICAL_CHART_CATALOG.filter((c) => c.group === group);
}

export function findChart(id: string): ClinicalChartDef | undefined {
  return CLINICAL_CHART_CATALOG.find((c) => c.id === id);
}
